//import MathLive from 'https://unpkg.com/mathlive/dist/mathlive.mjs';
const mf = MathLive.makeMathField(document.getElementById('mathfield'));
var el = mf.$el();
console.log("dom element:",el);
mf.$setConfig({'virtualKeyboardMode':'off','horizontalSpacingScale':2.0});
mf.$perform('hideVirtualKeyboard');

var buttonToLatex = {
    //num
    "1":"1",
    "2":"2",
    "3":"3",
    "4":"4",
    "5":"5",
    "6":"6",
    "7":"7",
    "8":"8",
    "9":"9",
    "0":"0",
    "{.}":".",
    "{bkts}": "\\left({#?}\\right)",
    //Basic
    "{square}": "^{2}",
    "{pow}": "^{{#?}}",
    "{x}": "x",
    "{x_pow2}":"x^2",
    "{x_pow3}":"x^3",
    "{y}": "y",
    "{y_pow2}": "y^2",
    "{y_pow3}": "y^3",
    "{e}": "e",
    "{pi}": "\\pi",
    "{theta}": "\\theta", 
    "{inf}": "\\infty",
    "{pm}":"\\pm",
    "{p}":"+",
    "{m}":"-",
    "{eq}":"=",
    "{div1}":"/",
    "{cdot}": "\\cdot",
    "{int}": "\\int ",
    "{d_int}": "\\int _{{#?}}^{{#?}}\\: ",
    "{sum}": "\\sum _{n={#?}}^{{#?}}",
    "{dx}": "{dx}",
    "{sqrt}":"\\sqrt{{#?}}",
    "{log}":"\\log _{#?}\\left(#?\\right)",
    
    //greek
    "{alpha}": "\\alpha",
    "{beta}": "\\beta", 
    "{gamma}": "\\gamma", 
    "{delta}": "\\delta", 
    "{zeta}": "\\zeta", 
    "{eta}": "\\eta", 
    //"{theta}": "\\theta", 
    "{iota}": "\\iota", 
    "{kappa}": "\\kappa", 
    "{lambda}": "\\lambda", 
    "{mu}": "\\mu",
    "{nu}": "\\nu", 
    "{xi}": "\\xi", 
    //"{pi}": "\\pi", 
    "{rho}": "\\rho", 
    "{sigma}": "\\sigma", 
    "{tau}": "\\tau", 
    "{upsilon}": "\\upsilon", 
    "{phi}": "\\phi", 
    "{chi}": "\\chi", 
    "{psi}": "\\psi", 
    "{omega}": "\\omega",

    //"{trigonometry}": "sincos",
    "{sin}": "\\sin\\left({#?}\\right)",
    "{cos}": "\\cos\\left({#?}\\right)",
    "{tan}": "\\tan\\left({#?}\\right)",
    "{cot}": "\\cot\\left({#?}\\right)",
    "{sec}": "\\sec\\left({#?}\\right)",
    "{csc}": "\\csc\\left({#?}\\right)",
    "{sinh}": "\\sinh\\left({#?}\\right)",
    "{cosh}": "\\cosh\\left({#?}\\right)",
    "{tanh}": "\\tanh\\left({#?}\\right)",
    "{coth}": "\\coth\\left({#?}\\right)",
    "{sech}": "\\sech\\left({#?}\\right)",
    "{arcsin}": "\\arcsin\\left({#?}\\right)",
    "{arccos}": "\\arccos\\left({#?}\\right)",
    "{arctan}": "\\arctan\\left({#?}\\right)",
    "{arccot}": "\\arccot\\left({#?}\\right)",
    "{arcsec}": "\\arcsec\\left({#?}\\right)",
    "{arccsc}": "\\arccsc\\left({#?}\\right)",
    "{arcsinh}": "\\arcsinh\\left({#?}\\right)",
    "{arccosh}": "\\arccosh\\left({#?}\\right)",
    "{arctanh}": "\\arctanh\\left({#?}\\right)",
    "{arccoth}": "\\arccoth\\left({#?}\\right)",
    "{arcsech}": "\\arcsech\\left({#?}\\right)",
    
    //operators
    //"{operators}": "≥÷→",
    // "{p}":"+",
    // "{m}":"-",
    // "{eq}":"=",
    // "{div1}":"/",
    "{div2}": "\\div",
    // "{cdot}": "\\cdot",
    "{times}": "\\times",
    "{les}":"<",
    "{mor}":">",
    "{le}": "\\le",
    "{ge}": "\\ge",
    "{pt}": "\\left({#?}\\right)", //(▢)
    "{sb}": "\\left[{#?}\\right]",	//[▢]
    "{longDiv}": "long\\:division\\:\\frac{{#?}}{{#1}}",
    //"{sqrt}":"\\sqrt{{#?}}",

    //"{bigOp}": "∑∫∏", 
    //"{int}": "\\int ",
    "{iint}": "\\int \\int \\:",
    "{iiint}": "\\int \\int \\int \\:",
    //"{d_int}": "\\int _{{#?}}^{{#1}}\\: ",
    "{d_iint}": "\\int _{{#?}}^{{#1}}\\int _{{#2}}^{{#3}}\\:",
    "{d_iiint}": "\\int _{{#?}}^{{#1}}\\int _{{#2}}^{{#3}}\\int _{{#4}}^{{#5}}\\:",
    //"{sum}": "\\sum _{n={#?}}^{{#1}}",
    "{lim}": "\\lim _{x\\to {#?} }\\left({#1}\\right)",
    "{deri_x}": "\\frac{d}{dx}\\left({#?}\\right)",//d(▢)/dx
    "{deri_x_2}": "\\frac{d^2}{dx^2}\\left({#?}\\right)",
    "{deri}": "\\left({#?}\\right)^'",
    "{deri_2}": "\\left({#?}\\right)^{''}",
    "{pderi}": "\\frac{\\partial }{\\partial x}\\left({#?}\\right)",
    // "{dx}": "{dx}",
    
}

var latex = mf.text('latext');
console.log("latex:", latex);